name: stocks_etfs_eye
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.8.0
  crypto: ^3.0.7
  dio: ^5.10.0
  equatable: ^2.1.0
  firebase_auth: ^6.5.7
  firebase_core: ^4.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_tabler_icons: ^1.43.0
  intl: ^0.20.2
  material_table_view: ^5.5.1
  shared_preferences: ^2.3.2
  timezone: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
