import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../cubit/locale_cubit.dart';
import 'format.dart';

/// All user-facing chrome strings in English + Arabic. Kept as a single small
/// lookup (≈60 strings) rather than the ARB/gen-l10n pipeline — at this size a
/// plain class is lighter, fully type-checked, and adds no build step.
///
/// Only static chrome is translated. Genuinely dynamic content (RSS headlines,
/// AI-written brief/take text, company names, tickers, prices) stays in its
/// source language — that's expected, not a gap.
class Strings {
  final bool ar;
  const Strings(this.ar);

  /// Reads the current language off the [LocaleCubit]. Uses `watch`, so a widget
  /// that reads a string *subscribes* to the language and rebuilds when it flips
  /// — this reaches through `const` ancestors (e.g. `const DashboardPage`) that
  /// a plain `read` + parent rebuild would skip. Call only during `build`.
  static Strings of(BuildContext context) =>
      Strings(context.watch<LocaleCubit>().isArabic);

  String _(String en, String arVal) => ar ? arVal : en;

  // ── Topbar ────────────────────────────────────────────────────────────────
  String get refresh => _('Refresh', 'تحديث');
  String get monitorSubtitle =>
      _('MULTI-MARKET MONITOR', 'مراقبة الأسواق المتعددة');
  String get utcLong =>
      _('Coordinated Universal Time', 'التوقيت العالمي المنسق');
  String openBadge(int open, int total) =>
      ar ? '$open / $total مفتوح' : '$open / $total open';

  // ── Dashboard shell ─────────────────────────────────────────────────────────
  String get marketsStatus => _('Markets — live status', 'الأسواق — الحالة المباشرة');
  String get watchlistTitle =>
      _('Watchlist · normalized to USD', 'قائمة المتابعة · بالدولار الأمريكي');
  String get watchlistNote => _(
        'Native currency shown with USD conversion beside it. FX rates are '
            'approximate (static) until a live FX source is wired.',
        'تُعرض العملة المحلية مع تحويلها إلى الدولار بجانبها. أسعار الصرف تقريبية '
            '(ثابتة) إلى أن يُربَط مصدر مباشر لأسعار العملات.',
      );
  String get footer => _(
        'Trading hours & weekends are per-market: KSA & Egypt trade Sun–Thu; USA, '
            'China & UAE trade Mon–Fri, China with a midday break. Gold ~24h Mon–Fri; '
            'Crypto is 24/7/365. Open/closed is computed live from your device clock.',
        'ساعات التداول والعطلات لكل سوق: السعودية ومصر تتداولان الأحد–الخميس؛ '
            'الولايات المتحدة والصين والإمارات الاثنين–الجمعة، والصين باستراحة منتصف اليوم. '
            'الذهب ~24 ساعة الاثنين–الجمعة؛ العملات الرقمية 24/7/365. تُحسب حالة الفتح/الإغلاق '
            'مباشرة من ساعة جهازك.',
      );
  String get failedToLoad => _('Failed to load dashboard', 'تعذّر تحميل اللوحة');
  String get retry => _('Retry', 'إعادة المحاولة');

  // ── Morning Brief ───────────────────────────────────────────────────────────
  String get briefTitle =>
      _('AI MORNING BRIEF', 'الموجز الصباحي بالذكاء الاصطناعي');
  String get todaysHint => _("Today's hint: ", 'إشارة اليوم: ');
  String get sources => _('SOURCES', 'المصادر');
  String get liveWebSearch => _('+ live web search', '+ بحث مباشر على الويب');
  String get plusWeb => _('+ web', '+ ويب');
  String briefWhen(String date, String time) => ar
      ? '· $date · حتى $time بتوقيت غرينتش'
      : '· $date · as of $time GMT';
  String liveLabel(String source) =>
      source == 'mock' ? 'mock' : _('$source + live web search', '$source + بحث مباشر');
  String briefAttribution(String live) => _(
        'Generated by AI ($live) from the market snapshot · '
            'Informational only, not investment advice.',
        'أُنشئ بالذكاء الاصطناعي ($live) من لقطة السوق · للاطلاع فقط، وليس نصيحة استثمارية.',
      );

  // ── Detail panel ────────────────────────────────────────────────────────────
  String leadingStocks(String currency) =>
      ar ? 'الأسهم القيادية · $currency' : 'Leading stocks · $currency';
  String get topMovers => _('Top movers · session', 'أبرز المتحركين · الجلسة');
  String get latestNews => _('Latest · news & sentiment', 'الأحدث · الأخبار والمشاعر');
  String get newsDisclaimer => _(
        'Headlines and sentiment are informational only — not investment advice.',
        'العناوين والمشاعر للاطلاع فقط — وليست نصيحة استثمارية.',
      );
  String get openNow => _('Open now', 'مفتوح الآن');
  String get closedNow => _('Closed', 'مغلق');
  String aiTake(String name) => ar ? 'رؤية الذكاء الاصطناعي · $name' : 'AI Take · $name';
  String ago(String published) => ar ? 'منذ $published' : '$published ago';

  // ── Screener ────────────────────────────────────────────────────────────────
  String get screenerTitle => _('Screener · all markets', 'الفارز · كل الأسواق');
  String instruments(int n) => ar ? '$n أداة' : '$n instruments';
  String get noMatches =>
      _('No instruments match these filters.', 'لا توجد أدوات تطابق هذه الفلاتر.');
  String get screenerNote => _(
        'Ranks the live movers & leaders already fetched per market. '
            'Tap a column to sort. Not investment advice.',
        'يرتّب المتحركين والأسهم القيادية المباشرة المجلوبة مسبقًا لكل سوق. '
            'اضغط على عمود للترتيب. ليست نصيحة استثمارية.',
      );
  String get filterAll => _('All', 'الكل');
  String get filterGainers => _('Gainers', 'الرابحون');
  String get filterLosers => _('Losers', 'الخاسرون');
  String get allMarkets => _('🌐 All', '🌐 الكل');
  String get searchHint => _('Search ticker / name', 'ابحث بالرمز / الاسم');

  // ── Market tile ─────────────────────────────────────────────────────────────
  String get tradesLabel => _('Trades', 'تداول');
  String get localLabel => _('Local', 'محلي');
  String get watch => _('Watch', 'متابعة');
  String get open => _('OPEN', 'مفتوح');
  String get closed => _('CLOSED', 'مغلق');

  // ── Table headers ───────────────────────────────────────────────────────────
  String get hMkt => _('Mkt', 'السوق');
  String get hTicker => _('Ticker', 'الرمز');
  String get hCompany => _('Company', 'الشركة');
  String get hPrice => _('Price', 'السعر');
  String get hChg => _('Chg', 'التغير');
  String get hDiv => _('Div', 'التوزيع');
  String get hDivYield => _('Div yield', 'عائد التوزيع');
  String get hSymbol => _('Symbol', 'الرمز');
  String get hNative => _('Native', 'محلي');
  String get hUsd => _('USD', 'دولار');

  List<String> get screenerHeaders =>
      [hMkt, hTicker, hCompany, hPrice, hChg, hDiv];
  List<String> get moversHeaders => [hTicker, hCompany, hChg];
  List<String> get leadersHeaders => [hTicker, hCompany, hPrice, hChg, hDivYield];
  List<String> get watchlistHeaders => [hSymbol, hNative, hUsd, hChg];

  // ── Sentiment ───────────────────────────────────────────────────────────────
  String sentiment(Sentiment s) => switch (s) {
        Sentiment.bull => _('Bullish', 'صاعد'),
        Sentiment.bear => _('Bearish', 'هابط'),
        Sentiment.neut => _('Neutral', 'محايد'),
      };
}

/// `context.s` → the current-language [Strings].
extension StringsContext on BuildContext {
  Strings get s => Strings.of(this);
}
