// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb0U6uRWCZVcqAJhSDfG7ZB7Gu9yawouI',
    appId: '1:1049316374463:web:59cf0c6f2310120c25d30a',
    messagingSenderId: '1049316374463',
    projectId: 'stocketfseye',
    authDomain: 'stocketfseye.firebaseapp.com',
    storageBucket: 'stocketfseye.firebasestorage.app',
    measurementId: 'G-F11GSQSXC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMES1rWstGJJrGC4EI0ItI5_yLtLC9NEI',
    appId: '1:1049316374463:android:d4abb6fe99ba3b4625d30a',
    messagingSenderId: '1049316374463',
    projectId: 'stocketfseye',
    storageBucket: 'stocketfseye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47Inikj9er5oYlcU_kp7C8SzEdVW4JU0',
    appId: '1:1049316374463:ios:f6c1af3c28d7867d25d30a',
    messagingSenderId: '1049316374463',
    projectId: 'stocketfseye',
    storageBucket: 'stocketfseye.firebasestorage.app',
    iosBundleId: 'com.example.stocksEtfsEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47Inikj9er5oYlcU_kp7C8SzEdVW4JU0',
    appId: '1:1049316374463:ios:f6c1af3c28d7867d25d30a',
    messagingSenderId: '1049316374463',
    projectId: 'stocketfseye',
    storageBucket: 'stocketfseye.firebasestorage.app',
    iosBundleId: 'com.example.stocksEtfsEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb0U6uRWCZVcqAJhSDfG7ZB7Gu9yawouI',
    appId: '1:1049316374463:web:7fbe03598033c50f25d30a',
    messagingSenderId: '1049316374463',
    projectId: 'stocketfseye',
    authDomain: 'stocketfseye.firebaseapp.com',
    storageBucket: 'stocketfseye.firebasestorage.app',
    measurementId: 'G-NQ57VLNNTX',
  );
}
