import 'package:flutter/material.dart';
import 'package:flutter_tabler_icons/flutter_tabler_icons.dart';
import 'package:intl/intl.dart';

import '../../app/theme.dart';
import '../../data/models/models.dart';
import 'common.dart';

/// The AI Morning Brief — a gold-accented roll-up across all markets.
class BriefCard extends StatelessWidget {
  final Brief brief;
  final DateTime asOf;

  const BriefCard({super.key, required this.brief, required this.asOf});

  String get _when {
    final d = asOf.toUtc();
    final date = DateFormat('EEE, d MMM yyyy').format(d);
    final time = DateFormat('HH:mm').format(d);
    return '· $date · as of $time GMT';
  }

  @override
  Widget build(BuildContext context) {
    final live =
        brief.source == 'mock' ? 'mock' : '${brief.source} + live web search';
    return Container(
      padding: const EdgeInsets.fromLTRB(22, 20, 22, 20),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppColors.accentDim),
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.accent.withValues(alpha: 0.07),
            AppColors.surface,
          ],
          stops: const [0, 0.6],
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _eyebrow(),
          const SizedBox(height: 13),
          Text(
            brief.lead,
            style: const TextStyle(
              fontSize: 14,
              color: AppColors.ink,
              height: 1.6,
            ),
          ),
          const SizedBox(height: 15),
          _lines(),
          const SizedBox(height: 15),
          _hint(),
          const SizedBox(height: 12),
          _citations(),
          const SizedBox(height: 12),
          Text(
            'Generated by AI ($live) from the market snapshot · '
            'Informational only, not investment advice.',
            style: const TextStyle(fontSize: 11, color: AppColors.ink3),
          ),
        ],
      ),
    );
  }

  Widget _eyebrow() => Row(
    children: [
      Container(
        width: 22,
        height: 22,
        decoration: BoxDecoration(
          color: AppColors.accent.withValues(alpha: 0.16),
          borderRadius: BorderRadius.circular(6),
          border: Border.all(color: AppColors.accentDim),
        ),
        child: const Icon(TablerIcons.sparkles, size: 12, color: AppColors.accent),
      ),
      const SizedBox(width: 9),
      Text(
        'AI MORNING BRIEF',
        style: AppText.label.copyWith(
          color: AppColors.accent,
          fontWeight: FontWeight.w700,
        ),
      ),
      const SizedBox(width: 8),
      Expanded(
        child: Text(
          _when,
          style: const TextStyle(fontSize: 11, color: AppColors.ink3),
          overflow: TextOverflow.ellipsis,
        ),
      ),
    ],
  );

  Widget _lines() => LayoutBuilder(
    builder: (context, c) {
      final twoCol = c.maxWidth > 560;
      final children = brief.lines.map(_line).toList();
      if (!twoCol) {
        return Column(children: children);
      }
      final mid = (children.length + 1) ~/ 2;
      return Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(child: Column(children: children.sublist(0, mid))),
          const SizedBox(width: 26),
          Expanded(child: Column(children: children.sublist(mid))),
        ],
      );
    },
  );

  Widget _line(BriefLine l) => Container(
    padding: const EdgeInsets.symmetric(vertical: 5),
    decoration: const BoxDecoration(
      border: Border(bottom: BorderSide(color: AppColors.line)),
    ),
    child: Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(l.flag, style: const TextStyle(fontSize: 14)),
        const SizedBox(width: 9),
        SizedBox(
          width: 46,
          child: Text(
            l.name,
            style: const TextStyle(
              fontSize: 12.5,
              fontWeight: FontWeight.w600,
              color: AppColors.ink,
            ),
          ),
        ),
        SentimentIcon(l.sentiment, size: 14),
        const SizedBox(width: 7),
        Expanded(
          child: Text(
            l.text,
            style: const TextStyle(fontSize: 12.5, color: AppColors.ink2),
          ),
        ),
      ],
    ),
  );

  Widget _hint() => Container(
    padding: const EdgeInsets.fromLTRB(14, 11, 14, 11),
    decoration: BoxDecoration(
      color: AppColors.accent.withValues(alpha: 0.08),
      borderRadius: const BorderRadius.only(
        topRight: Radius.circular(8),
        bottomRight: Radius.circular(8),
      ),
      border: const Border(
        left: BorderSide(color: AppColors.accent, width: 3),
      ),
    ),
    child: RichText(
      text: TextSpan(
        style: const TextStyle(fontSize: 13, color: AppColors.ink, height: 1.5),
        children: [
          const TextSpan(
            text: "Today's hint: ",
            style: TextStyle(
              color: AppColors.accent,
              fontWeight: FontWeight.w700,
            ),
          ),
          TextSpan(text: brief.hint),
        ],
      ),
    ),
  );

  Widget _citations() => Wrap(
    spacing: 6,
    runSpacing: 6,
    crossAxisAlignment: WrapCrossAlignment.center,
    children: [
      Text('SOURCES', style: AppText.label.copyWith(fontSize: 10)),
      for (final c in brief.citations) InfoChip(c),
      const InfoChip('+ live web search'),
    ],
  );
}
